// 表情仓库
export const qq = {
    '/:em:1': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/0.gif',
    '/:em:2': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/1.gif',
    '/:em:3': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/2.gif',
    '/:em:4': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/3.gif',
    '/:em:5': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/4.gif',
    '/:em:6': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/5.gif',
    '/:em:7': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/6.gif',
    '/:em:8': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/7.gif',
    '/:em:9': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/8.gif',
    '/:em:10': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/9.gif',
    '/:em:11': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/10.gif',
    '/:em:12': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/11.gif',
    '/:em:13': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/12.gif',
    '/:em:14': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/13.gif',
    '/:em:15': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/14.gif',
    '/:em:16': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/15.gif',
    '/:em:17': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/16.gif',
    '/:em:18': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/17.gif',
    '/:em:19': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/18.gif',
    '/:em:20': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/19.gif',
    '/:em:21': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/20.gif',
    '/:em:22': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/21.gif',
    '/:em:23': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/22.gif',
    '/:em:24': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/23.gif',
    '/:em:25': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/24.gif',
    '/:em:26': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/25.gif',
    '/:em:27': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/26.gif',
    '/:em:28': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/27.gif',
    '/:em:29': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/28.gif',
    '/:em:30': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/29.gif',
    '/:em:31': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/30.gif',
    '/:em:32': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/31.gif',
    '/:em:33': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/32.gif',
    '/:em:34': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/33.gif',
    '/:em:35': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/34.gif',
    '/:em:36': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/35.gif',
    '/:em:37': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/36.gif',
    '/:em:38': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/37.gif',
    '/:em:39': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/38.gif',
    '/:em:40': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/39.gif',
    '/:em:41': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/40.gif',
    '/:em:42': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/41.gif',
    '/:em:43': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/42.gif',
    '/:em:44': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/43.gif',
    '/:em:45': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/44.gif',
    '/:em:46': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/45.gif',
    '/:em:47': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/46.gif',
    '/:em:48': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/47.gif',
    '/:em:49': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/48.gif',
    '/:em:50': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/49.gif',
    '/:em:51': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/50.gif',
    '/:em:52': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/51.gif',
    '/:em:53': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/52.gif',
    '/:em:54': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/53.gif',
    '/:em:55': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/54.gif',
    '/:em:56': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/55.gif',
    '/:em:57': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/56.gif',
    '/:em:58': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/57.gif',
    '/:em:59': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/58.gif',
    '/:em:60': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/59.gif',
    '/:em:61': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/60.gif',
    '/:em:62': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/61.gif',
    '/:em:63': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/62.gif',
    '/:em:64': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/63.gif',
    '/:em:65': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/64.gif',
    '/:em:66': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/65.gif',
    '/:em:67': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/66.gif',
    '/:em:68': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/67.gif',
    '/:em:69': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/68.gif',
    '/:em:70': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/69.gif',
    '/:em:71': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/70.gif',
    '/:em:72': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/71.gif',
    '/:em:73': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/72.gif',
    '/:em:74': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/73.gif',
    '/:em:75': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/74.gif',
    '/:em:76': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/75.gif',
    '/:em:77': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/76.gif',
    '/:em:78': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/77.gif',
    '/:em:79': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/78.gif',
    '/:em:80': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/79.gif',
    '/:em:81': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/80.gif',
    '/:em:82': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/81.gif',
    '/:em:83': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/82.gif',
    '/:em:84': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/83.gif',
    '/:em:85': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/84.gif',
    '/:em:86': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/85.gif',
    '/:em:87': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/86.gif',
    '/:em:88': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/87.gif',
    '/:em:89': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/88.gif',
    '/:em:90': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/89.gif',
    // '/:em:91': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/90.gif',
    // '/:em:92': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/91.gif',
    // '/:em:93': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/92.gif',
    // '/:em:94': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/93.gif',
    // '/:em:95': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/94.gif',
    // '/:em:96': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/95.gif',
    // '/:em:97': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/96.gif',
    // '/:em:98': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/97.gif',
    // '/:em:99': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/98.gif',
    // '/:em:100': 'https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/99.gif' 
};

export const weixin = {

};